### ISSUE TITLE
Can not reproduce the result of zero shot classification

### ISSUE THREAD

**Issue by TangYuan96** [Mr-Neko/JM3D#1]
First, thanks for your sharing so good work!

I can not reproduce the result of zero shot classification
Are there any steps we need to pay attention to here ？

**Comment by TangYuan96** [comment]
![image](https://github.com/Mr-Neko/JM3D/assets/28919555/13ae4d59-bbcb-4f01-b6c3-9b82b110ec88)

**Comment by Mr-Neko** [comment]
Thanks for your attention! In fact, I do think I have taken wrong version of PointBert checkpoint. You can try the other checkpoints and I will vertify the right ckpt in few days. Sorry for the mistake. I post the training record here and wish it can help you. 
![PointBert训练图像](https://github.com/Mr-Neko/JM3D/assets/48724808/cd2f8fbd-eb19-4031-9a87-090d44b66bbb)
If there are anyting new, I will @ you to know it! Sorry again for the mistake!

**Comment by atomishcv** [comment]
@Mr-Neko I also encountered the same situation. Have you uploaded a new ckpt?

**Comment by Mr-Neko** [comment]
> @Mr-Neko I also encountered the same situation. Have you uploaded a new ckpt?

sorry for that, I will upload our new ckpts in a few weeks
