### ISSUE TITLE
A problem refers to "/root/3d_pretrain/data/PreTrain/ShapeNet/all.csv" in dataset_3d.py

### ISSUE THREAD

**Issue by KM-hanggg** [Mr-Neko/JM3D#2]
Hi, I think your work is very good and would like to reproduce your work.
I have a problem with this process:  In the dataset_3d.py file there is a piece of code that refers to the paths "/root/3d_pretrain/data/PreTrain/ShapeNet/all.csv",    "/root/3d_pretrain/data/PreTrain/ ShapeNet/Class2Labels.json",  I would like to change the location of these two files,  but I can't find them, can you please provide some help?

**Comment by Mr-Neko** [comment]
Thanks for your attention! That's my bad, I just upload the files in [./data](https://github.com/Mr-Neko/JM3D/tree/main/data) named ["ShapeNet_Class2Labels.json"](https://github.com/Mr-Neko/JM3D/blob/main/data/ShapeNet_Class2Labels.json) and [ShapeNet_all.csv](https://github.com/Mr-Neko/JM3D/blob/main/data/ShapeNet_all.csv). In fact, those files are the annotations that transfer text labels to the id for classification. I hope it will help you!:smiley:
