### ISSUE TITLE
 在预训练时遇到的问题

### ISSUE THREAD

**Issue by CChichoo** [Mr-Neko/JM3D#4]
作者团队你好，最近我在跟进项目时遇到了几个问题，如果方便的话可以为我解答一下吗：
    1.在对main.py进行调试的时候，在第一轮epoch训练结束之后弹出了一个错误，似乎是在加载val_loader的环节(line 227)发生了问题。请问有可能是因为数据集不干净而造成的吗？
    2.在查看上传的代码的时候，我发现了几个两周前上传的新文件，（ShpeNet_test.csv，ShapeNet_Label2Names.csv , val_shape_names,json等等) 但是这些文件没有在readme里面更新，请问要如何更改对应文件路径呢？
   由于能力有限，我在网上找了一些方法也没能解决问题（修改workers；在customized_collate_fn函数里添加过滤None数据的方法以及检查数据集路径），因此请求你们的协助。
![error](https://github.com/Mr-Neko/JM3D/assets/147399391/1f64638f-daf7-40c2-ab9f-96cfef8d30b9)

**Comment by Mr-Neko** [comment]
非常感谢您对我们工作的关注！关于您的问题我有几个可能的猜想和解决方案：
1. 关于您说的val_loader的问题，我们自己测试以及其他issue的复现中并没有提到过这个问题。我们的val_loader默认使用的是ModelNet40的数据。从bug记录来看，似乎是dataloader并没有读取到数据，所以您可能可以再检查一下测试数据的路径是否配置正确。
2. 这两个新文件其实是关于ShapeNet的一些类别的标注，将标注转化为序号标签，您可以自定义生成。您可以在最新的data/dataset_3d.py文件中的ShapeNet类中找到修改后的相对路径。这些文件只要放在data目录下就可以了，但是您需要更新您的dataset_3d.py文件。

希望我的回答可以帮助到您，有任何疑问，欢迎继续讨论~

**Comment by CChichoo** [comment]
好的，感谢您的解答！

**Comment by DeveloperLilili** [comment]
请问作者有JM3D的完整镜像可以拉取吗？

**Comment by Mr-Neko** [comment]
很抱歉，镜像文件都在公司服务器集群上，我现在恐怕没法提供给您！

**Comment by DeveloperLilili** [comment]
就您这边有比较完整的搭建流程吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月10日(星期二) 晚上9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mr-Neko/JM3D]  在预训练时遇到的问题 (Issue #4)





 
很抱歉，镜像文件都在公司服务器集群上，我现在恐怕没法提供给您！

**Comment by Mr-Neko** [comment]
Instruction 中的 Environments 中就是搭建的全部流程，您在搭建环境的时候遇到了什么问题吗？

**Comment by DeveloperLilili** [comment]
作者，您好，我想请问一下您这个有没有具体方向的应用，可以运用到什么场景，还有如果不介意的话能不能加个vx探讨一下，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月10日(星期二) 晚上9:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mr-Neko/JM3D]  在预训练时遇到的问题 (Issue #4)





 
Instruction 中的 Environments 中就是搭建的全部流程，您在搭建环境的时候遇到了什么问题吗？

**Comment by Mr-Neko** [comment]
可以的，我的微信号是Asuka_02W，欢迎讨论！




阍者
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr-Neko/JM3D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月11日(星期三) 上午10:24
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Mr-Neko/JM3D]  在预训练时遇到的问题 (Issue #4)





 作者，您好，我想请问一下您这个有没有具体方向的应用，可以运用到什么场景，还有如果不介意的话能不能加个vx探讨一下，谢谢！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年10月10日(星期二) 晚上9:40 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [Mr-Neko/JM3D]  在预训练时遇到的问题 (Issue #4) 
 
 
 
 
 
   
 Instruction 中的 Environments 中就是搭建的全部流程，您在搭建环境的时候遇到了什么问题吗？
