### ISSUE TITLE
What does "data argument" mean?

### ISSUE THREAD

**Issue by hiyyg** [Mr-Neko/JM3D#5]

**Comment by Mr-Neko** [comment]
Sorry for the late response! The data argument means the argument for 3D data, i.e., point cloud. We utilize the argument like rotate point cloud, shift, jitter, scale and so on. For more details, you can follow the 33-l31 line in the code of [dataset_3d.py](https://github.com/Mr-Neko/JM3D/tree/main/data/dataset_3d.py). Let me know this could help you!!!

**Comment by hiyyg** [comment]
Do you mean "augmentation" indeed? I don't get the word argument here.

**Comment by Mr-Neko** [comment]
You're right.  It's my typo! Thanks you for pointing out that! :cold_sweat:
